-- SCRIPT PARA BORRAR LOS USUARIOS Y ROLES CREADOS
DROP USER PACIENTE_ANTONIO;
DROP USER MEDICO_JUAN;
DROP USER GESTOR_PEDRO;
DROP USER ADMINISTRADOR_JUAN;
commit;

DROP ROLE PACIENTE;
DROP ROLE MEDICO;
DROP ROLE GESTOR_INFO;
DROP ROLE ADMIN_0711;
commit;